const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

const packageConfig = require(path.resolve(process.cwd(), 'package.json'));

const ParagonWebpackPlugin = require('../lib/plugins/paragon-webpack-plugin/ParagonWebpackPlugin');
const {
  getParagonThemeCss,
  getParagonCacheGroups,
  getParagonEntryPoints,
} = require('./data/paragonUtils');

const paragonThemeCss = getParagonThemeCss(process.cwd());
const brandThemeCss = getParagonThemeCss(process.cwd(), { isBrandOverride: true });

const tsconfigPath = path.resolve(process.cwd(), 'tsconfig.json');
const resolvePlugins = [];

// Conditionally add TsconfigPathsPlugin if tsconfig.json exists
if (fs.existsSync(tsconfigPath)) {
  resolvePlugins.push(new TsconfigPathsPlugin({ configFile: tsconfigPath }));
}

function getOverrides() {
  const overridesPath = path.resolve(__dirname, `../overrides/${packageConfig.name.replace('@edx/', '')}`);
  const overrides = [];

  function processDirectory(directory) {
    const files = fs.readdirSync(directory);

    files.forEach((file) => {
      const filePath = path.join(directory, file);
      const stats = fs.statSync(filePath);

      const relativePath = path.relative(overridesPath, filePath);
      const originalPath = path.join(process.cwd(), relativePath);

      if (stats.isFile()) {
        if (fs.existsSync(originalPath) && /\.(js|mjs|jsx|ts|tsx)$/.test(filePath)) {
          overrides.push({
            from: filePath,
            to: originalPath,
          });
        } else {
          try {
            fs.copyFileSync(filePath, originalPath);
            console.log('File was copied to destination', originalPath);
          } catch (err) {
            console.log(err);
          }
        }
      } else if (stats.isDirectory()) {
        try {
          if (!fs.existsSync(originalPath)) {
            fs.mkdirSync(originalPath, { recursive: true });
            console.log(originalPath, 'Directory created successfully!');
          }
        } catch (err) {
          console.error(err);
        }
        processDirectory(filePath); // Recursively process subdirectories
      }
    });
  }

  processDirectory(overridesPath);
  console.log('overrides', overrides);
  return overrides;
}

module.exports = {
  entry: {
    app: path.resolve(process.cwd(), './src/index'),
    /**
     * The entry points for the Paragon theme CSS. Example: ```
     * {
     *   "paragon.theme.core": "/path/to/node_modules/@openedx/paragon/dist/core.min.css",
     *   "paragon.theme.variants.light": "/path/to/node_modules/@openedx/paragon/dist/light.min.css"
     * }
     */
    ...getParagonEntryPoints(paragonThemeCss),
    /**
     * The entry points for the brand theme CSS. Example: ```
     * {
     *   "paragon.theme.core": "/path/to/node_modules/@(open)edx/brand/dist/core.min.css",
     *   "paragon.theme.variants.light": "/path/to/node_modules/@(open)edx/brand/dist/light.min.css"
     * }
     */
    ...getParagonEntryPoints(brandThemeCss),
  },
  output: {
    path: path.resolve(process.cwd(), './dist'),
    publicPath: '/',
  },
  resolve: {
    alias: {
      'env.config': path.resolve(process.cwd(), './env.config'),
    },
    fallback: {
      // This causes the system to return an empty object if it can't find an env.config.js file in
      // the application being built.
      'env.config': false,
    },
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    plugins: resolvePlugins,
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        ...getParagonCacheGroups(paragonThemeCss),
        ...getParagonCacheGroups(brandThemeCss),
      },
    },
  },
  plugins: [
    // RemoveEmptyScriptsPlugin get rid of empty scripts generated by webpack when using mini-css-extract-plugin
    // This helps to clean up the final bundle application
    // See: https://www.npmjs.com/package/webpack-remove-empty-scripts#usage-with-mini-css-extract-plugin
    new RemoveEmptyScriptsPlugin(),
    new ParagonWebpackPlugin(),
    ...getOverrides().map(({ from, to }) => (
      new webpack.NormalModuleReplacementPlugin(new RegExp(to), from)
    )),
  ],
  ignoreWarnings: [
    // Ignore warnings raised by source-map-loader.
    // some third party packages may ship miss-configured sourcemaps, that interrupts the build
    // See: https://github.com/facebook/create-react-app/discussions/11278#discussioncomment-1780169
    /**
     *
     * @param {import('webpack').WebpackError} warning
     * @returns {boolean}
     */
    function ignoreSourcemapsloaderWarnings(warning) {
      return (
        warning.module
        && warning.module.resource.includes('node_modules')
        && warning.details
        && warning.details.includes('source-map-loader')
      );
    },
  ],
};
